"""init

Revision ID: 981eabf1c020
Revises: 
Create Date: 2026-07-26 21:08:20.219607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '981eabf1c020'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
