"""init

Revision ID: d5de638dc22d
Revises: 981eabf1c020
Create Date: 2026-07-26 21:18:01.087354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd5de638dc22d'
down_revision: Union[str, None] = '981eabf1c020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
